Update noise.py from commit 730df0f
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\AI\\SDNEXT\\automatic\\extensions\\sd-webui-bmab-SDNEXT\\cache/noise_512_768.png'